// This file was autogenerated by calcdeps.py
goog.addDependency("../../../ydn-base/js/main.js", [], ['ydn.json', 'ydn.object']);
goog.addDependency("../../../ydn-base/js/ydn/async.js", ['ydn.async'], ['goog.async.Deferred', 'goog.async.DeferredList']);
goog.addDependency("../../../ydn-base/js/ydn/json.js", ['ydn.json'], ['goog.debug.Logger']);
goog.addDependency("../../../ydn-base/js/ydn/object.js", ['ydn.object'], ['ydn.json']);
goog.addDependency("../../../ydn-base/js/ydn/testing.js", ['ydn.testing'], ['goog.math']);
